package universidad.vistas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import universidad.entidades.Alumno;
import universidad.entidades.Inscripcion;
import universidad.entidades.Materia;

/**
 *
 * @author Grupo 61
 */
public class FormularioDeInscripciones extends javax.swing.JInternalFrame {

    private final DefaultTableModel modelo = new DefaultTableModel() {

        @Override
        public boolean isCellEditable(int f, int c) {

            return false;
        }
    };

    public FormularioDeInscripciones() {

        initComponents();
        cargarCB();
        armarTabla();
        jTFNota.setEditable(false);
        jTFNota.setVisible(false);
        jLNota.setVisible(false);
        jBAnular.setEnabled(false);
        jBInscribir.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bG = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCBAlumnos = new javax.swing.JComboBox<>();
        jBSalir = new javax.swing.JButton();
        jBAnular = new javax.swing.JButton();
        jBInscribir = new javax.swing.JButton();
        jRBNoInscriptas = new javax.swing.JRadioButton();
        jRBInscriptas = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLNota = new javax.swing.JLabel();
        jTFNota = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Formulario de Inscripciones");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Seleccione un alumno:");

        jCBAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBAlumnosActionPerformed(evt);
            }
        });

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jBAnular.setText("Anular Inscripcion");
        jBAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnularActionPerformed(evt);
            }
        });

        jBInscribir.setText("Inscribir");
        jBInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInscribirActionPerformed(evt);
            }
        });

        bG.add(jRBNoInscriptas);
        jRBNoInscriptas.setText("Materias NO Inscriptas");
        jRBNoInscriptas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBNoInscriptasMouseClicked(evt);
            }
        });

        bG.add(jRBInscriptas);
        jRBInscriptas.setText("Materias Inscriptas");
        jRBInscriptas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBInscriptasMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Listado de Materias");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLNota.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLNota.setText("Ingrese la nota del alumno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jCBAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRBInscriptas)
                        .addGap(122, 122, 122)
                        .addComponent(jRBNoInscriptas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBInscribir)
                        .addGap(95, 95, 95)
                        .addComponent(jBAnular)
                        .addGap(114, 114, 114)
                        .addComponent(jBSalir)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLNota)
                .addGap(18, 18, 18)
                .addComponent(jTFNota, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCBAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBNoInscriptas)
                    .addComponent(jRBInscriptas))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNota))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSalir)
                    .addComponent(jBAnular)
                    .addComponent(jBInscribir))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBAlumnosActionPerformed

        limpiarTabla();
        Alumno al = (Alumno) jCBAlumnos.getSelectedItem();
        cargarDatos(al.getId());
    }//GEN-LAST:event_jCBAlumnosActionPerformed

    private void jBAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAnularActionPerformed

        if (jTable1.getSelectedRow() == -1) {

            JOptionPane.showMessageDialog(this, "Seleccione una materia de la tabla");
            return;
        }

        try {
            
            Alumno al = (Alumno) jCBAlumnos.getSelectedItem();
            int filaS = jTable1.getSelectedRow();
            String nombre = (String) modelo.getValueAt(filaS, 1);
            Materia mat = Vista.getMD().buscarMateriaPorNombre(nombre);
            int registro = Vista.getID().borarInscripcionPorMateriaAlumno(al.getId(), mat.getId());
            if (registro > 0) {
                
                JOptionPane.showMessageDialog(this, "Se borro la inscripcion con exito");
            } else {
                
                JOptionPane.showMessageDialog(this, "No se pudo realizar esta operacion");
            }
            limpiarTabla();
            cargarDatos(al.getId());
        } catch (NumberFormatException e) {
            
            JOptionPane.showMessageDialog(this, "En el casillero nota solo deben ir numeros");
        }
    }//GEN-LAST:event_jBAnularActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jRBInscriptasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBInscriptasMouseClicked
        
        limpiarTabla();
        Alumno al = (Alumno) jCBAlumnos.getSelectedItem();
        cargarDatos(al.getId());
        
        jTFNota.setText("");
        jBInscribir.setEnabled(false);
        jBAnular.setEnabled(true);
        jTFNota.setEditable(false);
        jTFNota.setVisible(false);
        jLNota.setVisible(false);
    }//GEN-LAST:event_jRBInscriptasMouseClicked

    private void jRBNoInscriptasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBNoInscriptasMouseClicked
        
        limpiarTabla();
        Alumno al = (Alumno) jCBAlumnos.getSelectedItem();
        cargarDatos(al.getId());
        
        jBInscribir.setEnabled(true);
        jBAnular.setEnabled(false);
        jTFNota.setEditable(true);
        jTFNota.setVisible(true);
        jLNota.setVisible(true);
    }//GEN-LAST:event_jRBNoInscriptasMouseClicked

    private void jBInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInscribirActionPerformed
        
        if (jTFNota.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "El casillero Nota no debe estar vacio");
            return;
        } else if (jTable1.getSelectedRow() == -1) {
            
            JOptionPane.showMessageDialog(this, "Seleccione una materia de la tabla");
            return;
        }
        
        try {
            
            Alumno al = (Alumno) jCBAlumnos.getSelectedItem();
            int filaS = jTable1.getSelectedRow();
            String nombre = (String) modelo.getValueAt(filaS, 1);
            Materia mat = Vista.getMD().buscarMateriaPorNombre(nombre);
            double nota = Double.parseDouble(jTFNota.getText());
            Inscripcion insc = new Inscripcion(al, mat, nota);
            int registro = Vista.getID().guardarInscripcion(insc);
            if (registro > 0) {
                
                JOptionPane.showMessageDialog(this, "La inscripcion se realizo con exito");
            } else {
                
                JOptionPane.showMessageDialog(this, "La inscripcion ya esta realiza");
            }
            limpiarTabla();
            cargarDatos(al.getId());
        } catch (NumberFormatException e) {
            
            JOptionPane.showMessageDialog(this, "En el casillero nota solo deben ir numeros");
        }

        jTFNota.setText("");
    }//GEN-LAST:event_jBInscribirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bG;
    private javax.swing.JButton jBAnular;
    private javax.swing.JButton jBInscribir;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<Alumno> jCBAlumnos;
    private javax.swing.JLabel jLNota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRBInscriptas;
    private javax.swing.JRadioButton jRBNoInscriptas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFNota;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void cargarCB() {
        
        ArrayList<Alumno> Lista = Vista.getAD().listarAlumnos();
        for (Alumno al : Lista) {
            jCBAlumnos.addItem(al);
        }
    }

    private void armarTabla() {
        
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Año");
        jTable1.setModel(modelo);
    }

    private void cargarTabla(Materia mat) {
        
        modelo.addRow(new Object[]{
            mat.getId(),
            mat.getNombre(),
            Integer.toString(mat.getAnioMateria()),});
    }

    private void limpiarTabla() {
        
        int fila = modelo.getRowCount() - 1;
        for (int i = fila; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

    private void cargarDatos(int id) {
        
        if (jRBInscriptas.isSelected()) {
            
            ArrayList<Materia> Lista = Vista.getID().listarMateriasCursadas(id);
            for (Materia mat : Lista) {
                cargarTabla(mat);
            }
        } else if (jRBNoInscriptas.isSelected()) {
            
            ArrayList<Materia> Lista = Vista.getID().listarMateriasNoCursadas(id);
            for (Materia mat : Lista) {
                cargarTabla(mat);
            }
        }
    }
}
