package universidad.vistas;

import java.awt.Component;
import universidad.accesoADatos.AlumnoData;
import universidad.accesoADatos.InscripcionData;
import universidad.accesoADatos.MateriaData;

/**
 *
 * @author Grupo 61
 */
public class Vista extends javax.swing.JFrame {

    private static AlumnoData AD;
    private static MateriaData MD;
    private static InscripcionData ID;
    
    public Vista() {
        
        initComponents();
        AD = new AlumnoData();
        MD = new MateriaData();
        ID = new InscripcionData();
    }

    public static AlumnoData getAD() {
        return AD;
    }

    public static MateriaData getMD() {
        return MD;
    }

    public static InscripcionData getID() {
        return ID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMIFormularioDeAlumno = new javax.swing.JMenuItem();
        jMIEdicionDeAlumno = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMIFormularioDeMateria = new javax.swing.JMenuItem();
        jMIEdicionDeMateria = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMIManejoDeInscripciones = new javax.swing.JMenuItem();
        jMIManejoDeNotas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMIAlumnosPorMateria = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jMenu2.setText("Alumnos");

        jMIFormularioDeAlumno.setText("Formulario de Alumno");
        jMIFormularioDeAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIFormularioDeAlumnoActionPerformed(evt);
            }
        });
        jMenu2.add(jMIFormularioDeAlumno);

        jMIEdicionDeAlumno.setText("Edicion de Alumno");
        jMIEdicionDeAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIEdicionDeAlumnoActionPerformed(evt);
            }
        });
        jMenu2.add(jMIEdicionDeAlumno);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Materias");

        jMIFormularioDeMateria.setText("Formulario de Materia ");
        jMIFormularioDeMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIFormularioDeMateriaActionPerformed(evt);
            }
        });
        jMenu3.add(jMIFormularioDeMateria);

        jMIEdicionDeMateria.setText("Edicion de Materia");
        jMIEdicionDeMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIEdicionDeMateriaActionPerformed(evt);
            }
        });
        jMenu3.add(jMIEdicionDeMateria);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Administracion");

        jMIManejoDeInscripciones.setText("Manejo de Inscripciones");
        jMIManejoDeInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIManejoDeInscripcionesActionPerformed(evt);
            }
        });
        jMenu1.add(jMIManejoDeInscripciones);

        jMIManejoDeNotas.setText("Manejo de Notas");
        jMIManejoDeNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIManejoDeNotasActionPerformed(evt);
            }
        });
        jMenu1.add(jMIManejoDeNotas);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Consultas");

        jMIAlumnosPorMateria.setText("Alumnos por Materia");
        jMIAlumnosPorMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAlumnosPorMateriaActionPerformed(evt);
            }
        });
        jMenu4.add(jMIAlumnosPorMateria);

        jMenuBar1.add(jMenu4);

        jMSalir.setText("Salir");
        jMSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIFormularioDeMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIFormularioDeMateriaActionPerformed
        
        GestionDeMaterias GDM = new GestionDeMaterias();
        abrirVentana(GDM);
    }//GEN-LAST:event_jMIFormularioDeMateriaActionPerformed

    private void jMIManejoDeNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIManejoDeNotasActionPerformed
        
        ManejoDeNotas MDN = new ManejoDeNotas();
        abrirVentana(MDN);
    }//GEN-LAST:event_jMIManejoDeNotasActionPerformed

    private void jMIAlumnosPorMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAlumnosPorMateriaActionPerformed
        
        ListadoDeAlumnoPorMateria LAM = new ListadoDeAlumnoPorMateria();
        abrirVentana(LAM);
    }//GEN-LAST:event_jMIAlumnosPorMateriaActionPerformed

    private void jMIEdicionDeAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIEdicionDeAlumnoActionPerformed

        EdicionDeAlumno EDA = new EdicionDeAlumno();
        abrirVentana(EDA);
    }//GEN-LAST:event_jMIEdicionDeAlumnoActionPerformed

    private void jMIEdicionDeMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIEdicionDeMateriaActionPerformed

        EdicionDeMateria EDM = new EdicionDeMateria();
        abrirVentana(EDM);
    }//GEN-LAST:event_jMIEdicionDeMateriaActionPerformed

    private void jMIFormularioDeAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIFormularioDeAlumnoActionPerformed

        GestionDeAlumnos GDA = new GestionDeAlumnos();
        abrirVentana(GDA);
    }//GEN-LAST:event_jMIFormularioDeAlumnoActionPerformed

    private void jMSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMSalirMouseClicked

        SalirView exit = new SalirView();
        abrirVentana(exit);
    }//GEN-LAST:event_jMSalirMouseClicked

    private void jMIManejoDeInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIManejoDeInscripcionesActionPerformed

        FormularioDeInscripciones FDI = new FormularioDeInscripciones();
        abrirVentana(FDI);
    }//GEN-LAST:event_jMIManejoDeInscripcionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jMIAlumnosPorMateria;
    private javax.swing.JMenuItem jMIEdicionDeAlumno;
    private javax.swing.JMenuItem jMIEdicionDeMateria;
    private javax.swing.JMenuItem jMIFormularioDeAlumno;
    private javax.swing.JMenuItem jMIFormularioDeMateria;
    private javax.swing.JMenuItem jMIManejoDeInscripciones;
    private javax.swing.JMenuItem jMIManejoDeNotas;
    private javax.swing.JMenu jMSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    private void abrirVentana(Component cpm){
        escritorio.removeAll();
        escritorio.repaint();
        cpm.setVisible(true);
        escritorio.add(cpm);
        escritorio.moveToFront(cpm);
    }
}
